
import java.io.File;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author olymer
 */
public class VagrantDeductor3installations extends javax.swing.JFrame {

    /**
     * Creates new form VagrantDeductor
     */
    public VagrantDeductor3installations() {
        initComponents();
        ifInfobox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        ifInfobox = new javax.swing.JInternalFrame();
        lblInfobox = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbPsql = new javax.swing.JCheckBox();
        cbApt = new javax.swing.JCheckBox();
        cbMysql = new javax.swing.JCheckBox();
        cbOpenssl = new javax.swing.JCheckBox();
        cbApache = new javax.swing.JCheckBox();
        cbPhp5 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 60));

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 60, 60));

        ifInfobox.setClosable(true);
        ifInfobox.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ifInfobox.setTitle("VagrantDestructor");
        ifInfobox.setVisible(false);

        lblInfobox.setText(" ");

        org.jdesktop.layout.GroupLayout ifInfoboxLayout = new org.jdesktop.layout.GroupLayout(ifInfobox.getContentPane());
        ifInfobox.getContentPane().setLayout(ifInfoboxLayout);
        ifInfoboxLayout.setHorizontalGroup(
            ifInfoboxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ifInfoboxLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblInfobox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 266, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ifInfoboxLayout.setVerticalGroup(
            ifInfoboxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ifInfoboxLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(lblInfobox)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel3.add(ifInfobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 130));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Preinstallations");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("3/7");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        cbPsql.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        cbPsql.setText("psql");
        jPanel3.add(cbPsql, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        cbApt.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        cbApt.setText("apt");
        jPanel3.add(cbApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        cbMysql.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        cbMysql.setText("mysql");
        jPanel3.add(cbMysql, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        cbOpenssl.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        cbOpenssl.setText("openssl");
        jPanel3.add(cbOpenssl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        cbApache.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        cbApache.setText("apache");
        jPanel3.add(cbApache, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        cbPhp5.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        cbPhp5.setText("php5");
        jPanel3.add(cbPhp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("not implemented yet");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 260, 60));

        jLabel11.setText(":..");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
            if (cbMysql.isSelected()) {
                Global.preinstallHistoryMysql = true;
                Global.logh1 = "Mysql: YES";
            } else {
                Global.preinstallHistoryMysql = false;
                Global.logh1 = "Mysql: NO";
            }
            if (cbPsql.isSelected()) {
                Global.preinstallHistorypsql = true;
                Global.logh2 = "Psql: YES";
            } else {
                Global.preinstallHistorypsql = false;
                Global.logh2 = "Psql: NO";
            }
            if (cbApt.isSelected()) {
                Global.preinstallHistoryapt = true;
                Global.logh3 = "Apt: YES";
            } else {
                Global.preinstallHistoryapt = false;
                Global.logh3 = "Apt: NO";
            }
            if (cbOpenssl.isSelected()) {
                Global.preinstallHistoryopenssl = true;
                Global.logh4 = "OpenSSL: YES";
            } else {
                Global.preinstallHistoryopenssl = false;
                Global.logh4 = "OpenSSL: NO";
            }
            if (cbPhp5.isSelected()) {
                Global.preinstallHistoryphp5 = true;
                Global.logh5 = "PHP5: YES";
            } else {
                Global.preinstallHistoryphp5 = false;
                Global.logh5 = "PHP5: NO";
            }
            if (cbApache.isSelected()) {
                Global.preinstallHistoryapache = true;
                Global.logh6 = "Apache: YES";
            } else {
                Global.preinstallHistoryapache = false;
                Global.logh6 = "Apache: NO";
            }
            if (cbMysql.isSelected()==false && cbPsql.isSelected()==false && cbApt.isSelected()==false && cbOpenssl.isSelected()==false && cbPhp5.isSelected()==false && cbApache.isSelected()==false) {
                Global.step4empty = true;
            } else {
                Global.step4empty = false;
            }
            new VagrantDeductor4installations().setVisible(true);
            this.setVisible(false);
            this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new VagrantDeductor2installations().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VagrantDeductor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JCheckBox cbApache;
    private javax.swing.JCheckBox cbApt;
    private javax.swing.JCheckBox cbMysql;
    private javax.swing.JCheckBox cbOpenssl;
    private javax.swing.JCheckBox cbPhp5;
    private javax.swing.JCheckBox cbPsql;
    private javax.swing.JInternalFrame ifInfobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInfobox;
    // End of variables declaration//GEN-END:variables
}
