

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author olymer
 */
public class VagrantDeductor extends javax.swing.JFrame {

    /**
     * Creates new form VagrantDeductor
     */
    public VagrantDeductor() {
        initComponents();
        detectOS();
        ifInfobox.setVisible(false);
        ifSettings.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        ifInfobox = new javax.swing.JInternalFrame();
        lblInfobox = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        ifAbout = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAbout = new javax.swing.JButton();
        ifSettings = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        settingPopup = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("VagrantDeductor");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 60));

        ifInfobox.setClosable(true);
        ifInfobox.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ifInfobox.setTitle("VagrantDestructor");
        ifInfobox.setVisible(false);

        lblInfobox.setText(" ");

        org.jdesktop.layout.GroupLayout ifInfoboxLayout = new org.jdesktop.layout.GroupLayout(ifInfobox.getContentPane());
        ifInfobox.getContentPane().setLayout(ifInfoboxLayout);
        ifInfoboxLayout.setHorizontalGroup(
            ifInfoboxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ifInfoboxLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblInfobox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 266, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ifInfoboxLayout.setVerticalGroup(
            ifInfoboxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ifInfoboxLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(lblInfobox)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel3.add(ifInfobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 130));

        btnSettings.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSettings.setText("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        jPanel3.add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 350, 60));

        ifAbout.setClosable(true);
        ifAbout.setTitle("About");
        ifAbout.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("VagrantDeductor is a GUI to build Vagrant ");

        jLabel3.setText("projects in seven simple Steps.");

        jLabel4.setText("2012");

        jLabel5.setText(":..");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(69, 69, 69)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel4)
                        .add(48, 48, 48))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLabel5))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout ifAboutLayout = new org.jdesktop.layout.GroupLayout(ifAbout.getContentPane());
        ifAbout.getContentPane().setLayout(ifAboutLayout);
        ifAboutLayout.setHorizontalGroup(
            ifAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ifAboutLayout.setVerticalGroup(
            ifAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, ifAboutLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(ifAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 350, 130));

        jLabel11.setText(":..");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        btnAbout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jPanel3.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 350, 60));

        ifSettings.setClosable(true);
        ifSettings.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        settingPopup.setText("Open projectfolder when setup is finished");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(settingPopup)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(settingPopup)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout ifSettingsLayout = new org.jdesktop.layout.GroupLayout(ifSettings.getContentPane());
        ifSettings.getContentPane().setLayout(ifSettingsLayout);
        ifSettingsLayout.setHorizontalGroup(
            ifSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ifSettingsLayout.setVerticalGroup(
            ifSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(ifSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 350, 150));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (settingPopup.isSelected()) {
            Global.settingPopup = true;
        } else {
            Global.settingPopup = false;
        }
        
         new VagrantDeductor1installations().setVisible(true);
         this.setVisible(false);
         this.disable();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        ifSettings.setVisible(true);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        ifAbout.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VagrantDeductor().setVisible(true);
            }
        });
    }
    
    public static void detectOS() {
        String os = System.getProperty("os.name").toLowerCase();
        if (os.indexOf("win") >= 0) {
            Global.os = "Windows";
        } else if (os.indexOf("mac") >= 0) {
            Global.os = "Mac";
        } else if (os.indexOf("nix") >= 0 || os.indexOf("nux") >= 0) {
            Global.os = "UNIX based";
        } else if (os.indexOf("sunos") >= 0) {
            Global.os = "Solaris";
        }
        Global.log1 = "VagrantDeductor is running on a " + Global.os + " operating system";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSettings;
    private javax.swing.JInternalFrame ifAbout;
    private javax.swing.JInternalFrame ifInfobox;
    private javax.swing.JInternalFrame ifSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInfobox;
    private javax.swing.JCheckBox settingPopup;
    // End of variables declaration//GEN-END:variables

}
