/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
/**
 *
 * @author olymer
 */
public class VagrantDeductor1installations extends javax.swing.JFrame {

    public boolean tbtnForwardedToggled;
    /**
     * Creates new form VagrantDeductor
     */
    public VagrantDeductor1installations() {
        initComponents();
        tbtnForwardedToggled = true;
        if (Global.port.equals("")) {
            tfPort.setText("5432");
        } else {
            tfPort.setText(Global.port);
        }
        if (Global.portforwarding.charAt(0) == '#') {
            tfPort.setVisible(false);
            tbtnForwardedToggled = false;
            tbtnForwarding.setText("OFF");
            lablePortinfo.setText("Portforwarding disabled");
        } else {
            tfPort.setVisible(true);
            tbtnForwardedToggled = true;
            tbtnForwarding.setText("ON");
            lablePortinfo.setText("Port 80 to");
        }
        ifInfobox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tbtnForwarding = new javax.swing.JToggleButton();
        lablePortinfo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ifInfobox = new javax.swing.JInternalFrame();
        lblInfobox = new javax.swing.JLabel();
        tfPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 60));

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 60, 60));

        tbtnForwarding.setText("ON");
        tbtnForwarding.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbtnForwardingStateChanged(evt);
            }
        });
        tbtnForwarding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnForwardingActionPerformed(evt);
            }
        });
        jPanel3.add(tbtnForwarding, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 60));

        lablePortinfo.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lablePortinfo.setText("Port 80 to");
        jPanel3.add(lablePortinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Portforwarding");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        ifInfobox.setClosable(true);
        ifInfobox.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ifInfobox.setTitle("VagrantDestructor");
        ifInfobox.setVisible(false);

        lblInfobox.setText(" ");

        org.jdesktop.layout.GroupLayout ifInfoboxLayout = new org.jdesktop.layout.GroupLayout(ifInfobox.getContentPane());
        ifInfobox.getContentPane().setLayout(ifInfoboxLayout);
        ifInfoboxLayout.setHorizontalGroup(
            ifInfoboxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ifInfoboxLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblInfobox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 266, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ifInfoboxLayout.setVerticalGroup(
            ifInfoboxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ifInfoboxLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(lblInfobox)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel3.add(ifInfobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tfPort.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jPanel3.add(tfPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 160, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("1/7");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel11.setText(":..");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new VagrantDeductor().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // goto next step
        if (tbtnForwarding.getText().equals("ON")) {
            // Todo: check for numeric
            if (tfPort.getText().equals("")) {
                ifInfobox.setVisible(true);
                lblInfobox.setText("Please enter a Portnumber");
            } else {
                lablePortinfo.setText("Port 80 to");
                tfPort.setVisible(true);
                try  
                {  
                    Integer.parseInt(tfPort.getText());   
                    Global.portforwarding = "config.vm.forward_port 80, " + tfPort.getText();
                    Global.portHistory = tfPort.getText();
                    new VagrantDeductor2installations().setVisible(true);
                    this.setVisible(false);
                    this.disable();
                    Global.log3 = "Port 80 will be forwarted to: " + tfPort.getText();
                }  
                catch(Exception e)  
                {  
                    ifInfobox.setVisible(true);
                    lblInfobox.setText("Please enter a Portnumber");
                }  
            }
        } else {
            lablePortinfo.setText("Portforwarding disabled");
            tfPort.setVisible(false);
            tbtnForwarding.setText("OFF");
            Global.portforwarding = "# config.vm.forward_port 80, 5432";
            new VagrantDeductor2installations().setVisible(true);
            this.setVisible(false);
            this.disable();
            Global.log3 = "Portforwarding: disabled";
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void tbtnForwardingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnForwardingActionPerformed
        // Button toggled
        if (tbtnForwardedToggled) {
            lablePortinfo.setText("Portforwarding disabled");
            tfPort.setVisible(false);
            tbtnForwardedToggled = false;
            tbtnForwarding.setText("OFF");
        } else {
            lablePortinfo.setVisible(true);
            tfPort.setVisible(true);
            lablePortinfo.setText("Port 80 to");
            tbtnForwardedToggled = true;
            tbtnForwarding.setText("ON");
        }
    }//GEN-LAST:event_tbtnForwardingActionPerformed

    private void tbtnForwardingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbtnForwardingStateChanged

    }//GEN-LAST:event_tbtnForwardingStateChanged


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VagrantDeductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VagrantDeductor1installations().setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JInternalFrame ifInfobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lablePortinfo;
    private javax.swing.JLabel lblInfobox;
    private javax.swing.JToggleButton tbtnForwarding;
    private javax.swing.JTextField tfPort;
    // End of variables declaration//GEN-END:variables
}
